development:
  adapter: postgresql
  encoding: unicode
  database: ads_development
  pool: 5
  timeout: 5000
  username: yegor_zdanovich
  password: 'postgres'

test:
  adapter: postgresql
  encoding: unicode
  database: ads_test
  pool: 5
  timeout: 5000
  username: yegor_zdanovich
  password: 'postgres'

production:
  adapter: postgresql
  encoding: unicode
  database: ads_production
  pool: 5
  timeout: 5000
  username: yegor_zdanovich
  password: 'postgres'